name: Performance

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  benchmark:
    runs-on: mi300

    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: Setup venv
        run: |
          python3.11 -m venv bench_venv
          source bench_venv/bin/activate
          pip install --find-links https://iree.dev/pip-release-links.html iree-compiler iree-runtime --upgrade
          pip install -r requirements.txt
          pip install --no-compile --pre --upgrade -e common_tools

      - name: Convolutions
        run: |
          source bench_venv/bin/activate
          python convbench/shark_conv.py

      - name: Attention
        run: |
          source bench_venv/bin/activate
          python attentionbench/attention_bench.py

      - name: GEMM
        run: |
          source bench_venv/bin/activate
          python gemmbench/gemm_bench.py

      - name: Roofline Plots
        run: |
          source bench_venv/bin/activate
          python convbench/shark_conv.py --roofline results/iree_conv.csv --plot results/iree_conv.png
          python convbench/shark_conv.py --roofline results/iree_attention.csv --plot results/iree_attention.png
          python convbench/shark_conv.py --roofline results/iree_gemm.csv --plot results/iree_gemm.png
          python convbench/shark_conv.py --roofline results/iree_gemm.csv,results/iree_attention.csv,results/iree_conv.csv --plot results/combined.png

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: ./results/
